name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    env:
      CHERE_INVOKING: '1'
      CYGWIN_NOWINPATH: '1'

    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

    steps:
      - name: Force LF line endings in initial checkout
        shell: pwsh  # Do this outside Cygwin, to affect actions/checkout.
        run: git config --global core.autocrlf false

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v5
        with:
          packages: >-
            python39
            python-pip-wheel
            python-setuptools-wheel
            python-wheel-wheel
          add-to-path: false

      - name: Set up virtual environment
        run: |
          python3.9 -m venv .venv
          echo 'BASH_ENV=.venv/bin/activate' >>"$GITHUB_ENV"

      - name: Upgrade PyPA packages
        run: python -m pip install -U pip setuptools wheel

      - name: Install project and dependencies
        run: pip install .

      - name: Run failing test
        run: |
          ! pytest --color=yes -vv test_indirect.py::test_subprocess

      - name: Run passing test
        run: pytest --color=yes -vv test_indirect.py::test_subprocess_nosite
