name: Test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    env:
      CHERE_INVOKING: '1'
      CYGWIN_NOWINPATH: '1'

    defaults:
      run:
        shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'

    steps:
      - name: Force LF line endings in initial checkout
        shell: pwsh  # Do this outside Cygwin, to affect actions/checkout.
        run: git config --global core.autocrlf false

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v5
        with:
          packages: >-
            _autorebase
            alternatives
            base-cygwin
            base-files
            bash
            binutils
            bzip2
            ca-certificates
            cmake
            coreutils
            crypto-policies
            csih
            cygrunsrv
            cygutils
            cygwin
            cygwin-debuginfo
            cygwin-devel
            dash
            dejavu-fonts
            desktop-file-utils
            diffutils
            dos2unix
            editrights
            file
            findutils
            gamin
            gawk
            gcc-core
            gcc-fortran
            gcc-g++
            getent
            gettext
            git
            gnupg2
            grep
            groff
            gsettings-desktop-schemas
            gzip
            hostname
            info
            ipc-utils
            keychain
            less
            libarchive13
            libargp
            libassuan0
            libassuan9
            libatomic1
            libattr1
            libblkid1
            libbrotlicommon1
            libbrotlidec1
            libbz2_1
            libcares2
            libcharset1
            libcom_err2
            libcrypt-devel
            libcrypt2
            libcurl4
            libdb18.1
            libdb5.3
            libdeflate0
            libedit0
            libexpat1
            libfam0
            libfdisk1
            libffi-devel
            libffi6
            libffi8
            libfido2
            libfontconfig-common
            libfontconfig1
            libfreetype6
            libfribidi0
            libgc1
            libgcc1
            libgcrypt20
            libgdbm6
            libgdbm_compat4
            libgfortran5
            libglib2.0_0
            libgmp10
            libgnutls30
            libgomp1
            libgpg-error0
            libgpgme11
            libgraphite2_3
            libgsasl-common
            libgsasl18
            libgssapi_krb5_2
            libguile3.0_1
            libharfbuzz0
            libhogweed6
            libiconv-devel
            libiconv2
            libidn12
            libidn2_0
            libimagequant0
            libintl-devel
            libintl8
            libisl23
            libjbig2
            libjpeg8
            libjsoncpp25
            libk5crypto3
            libkrb5_3
            libkrb5support0
            libksba8
            liblapack-devel
            liblapack0
            liblastlog2
            liblcms2_2
            liblz4_1
            liblzma5
            liblzo2_2
            libmetalink3
            libmpc3
            libmpfr6
            libncursesw10
            libnettle8
            libnghttp2_14
            libnpth0
            libntlm0
            libopenldap2
            libopenldap2_4_2
            libp11-kit0
            libpcre1
            libpcre2_8_0
            libpipeline1
            libpkgconf4
            libpkgconf5
            libpkgconf6
            libpng16
            libpopt-common
            libpopt0
            libpsl5
            libquadmath0
            libraqm0
            libreadline7
            librhash0
            libsasl2_3
            libsigsegv2
            libsmartcols1
            libsodium-common
            libsodium23
            libsqlite3_0
            libssh2_1
            libssl1.1
            libssl3
            libstdc++6
            libtasn1_6
            libtiff6
            libtiff7
            libuchardet0
            libunistring5
            libusb1.0
            libuuid1
            libuv1
            libwebp7
            libwebpdemux2
            libwebpmux3
            libX11_6
            libXau6
            libxcb1
            libXdmcp6
            libXext6
            libXft2
            libxml2
            libXrender1
            libXss1
            libxxhash0
            libzstd1
            login
            make
            man-db
            mintty
            ncurses
            ninja
            openssh
            openssl
            p11-kit
            p11-kit-trust
            perl
            perl-Error
            perl-TermReadKey
            perl_autorebase
            perl_base
            pinentry
            pkg-config
            pkgconf
            publicsuffix-list-dafsa
            python-pip-wheel
            python-setuptools-wheel
            python-wheel-wheel
            python39
            python39-babel
            python39-cachetools
            python39-certifi
            python39-chardet
            python39-colorama
            python39-devel
            python39-distlib
            python39-docutils
            python39-filelock
            python39-idna
            python39-imagesize
            python39-imaging
            python39-iniconfig
            python39-jinja2
            python39-markupsafe
            python39-olefile
            python39-packaging
            python39-pip
            python39-platformdirs
            python39-pluggy
            python39-py
            python39-pygments
            python39-pyparsing
            python39-pyproject_api
            python39-pytest
            python39-railroad-diagrams
            python39-requests
            python39-setuptools
            python39-six
            python39-snowballstemmer
            python39-sphinx
            python39-sphinxcontrib-serializinghtml
            python39-toml
            python39-tox
            python39-typing_extension
            python39-urllib3
            python39-virtualenv
            python39-wheel
            python39-zipp
            rebase
            rsync
            run
            sed
            shared-mime-info
            tar
            tcl
            tcl-tix
            tcl-tk
            terminfo
            tzcode
            tzdata
            util-linux
            vim
            vim-common
            vim-minimal
            w32api-headers
            w32api-runtime
            wget
            which
            windows-default-manifest
            xxd
            xz
            zlib0
            zstd
          add-to-path: false

      - name: List all installed Cygwin packages
        run: cygcheck -n

      #- name: Upgrade PyPA packages systemwide
      #  run: |
      #    python3.9 -m pip install -U pip setuptools wheel

      # - name: Set up virtual environment
      #   run: |
      #     python3.9 -m venv .venv
      #     echo 'BASH_ENV=.venv/bin/activate' >>"$GITHUB_ENV"

      - name: Set up virtual environment
        run: |
          python3.9 -m venv --without-pip .venv
          echo BASH_ENV=.venv/bin/activate >>"$GITHUB_ENV"

      - name: Show `$BASH_ENV` and `python` location
        run: |
          set -x
          printenv BASH_ENV
          type python

      # - uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      - name: Install pip
        run: python -m ensurepip
